name: Deploy to Pages Branch

on:
  # 每次推送到 `custom` 分支时触发这个"工作流程"
  push:
    branches: [ custom ]
  # 允许你在 GitHub 上的 Actions 标签中手动触发此"工作流程"
  workflow_dispatch:

# 需要写入权限来推送到pages分支
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
          run_install: false
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build site
        run: pnpm run build
      
      - name: Deploy to pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAT }} # 需要在仓库的Settings->Secrets and variables->Actions中添加GH_PAT，该Token需要有写入权限
          repository-name: xpfxzxc/xpfxzxc.github.io # 你的GitHub Pages仓库名称
          branch: main # 部署到custom分支
          folder: dist # Astro默认构建输出目录
          clean: true # 清理目标分支中的旧文件
